language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
    - "pypy"
    # - "pypy3" Not supported by pip/virtualenv yet

install:
  - pip install pipenv>=4.0 virtualenv>=12.0.2

script:
  - pipenv check
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
  - ./test.sh
